# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf799ee50dcb4f7198f36209e1fb673cc0437840a1bebbc2dd682a3466b34e93163d84fbb2c8482ddcf8aca82d06aa400e66124162d8234e433f3a2dd09e33ad

test:
  secret_key_base: 8b809d261a83c03c8cf4d163911c702e15ffd94b73f137fa36c898efba548de961fe4a785e7dfa76dee0431a0293104f80764337d94af032e56d86120beceb73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
